name: Pre-commit checks

on:
  push:
    branches: [main]
    paths:
      - ".pre-commit-config.yaml"
      - ".github/workflows/pre-commit.yml"

  pull_request:
    branches: [main]

  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.3.0
        with:
          enable-cache: true
          python-version: "3.14"

      - name: Set UTF-8 encoding
        run: echo "PYTHONUTF8=1" >> $GITHUB_ENV

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files

